language: python

# Test environments
matrix:
  include:
    - env: TOXENV=py27-dj17
    - env: TOXENV=py33-dj17
    - env: TOXENV=py34-dj17
    - env: TOXENV=py27-dj18
    - env: TOXENV=py33-dj18
    - env: TOXENV=py34-dj18

# Package installation
install:
  - pip install tox coveralls

# Run tests
script:
  - tox

# Call subsequent services
after_success:
  - coveralls
