language: python
sudo: true

# Test environments
matrix:
  include:
    - env: TOXENV=py27-dj17
    - env: TOXENV=py33-dj17
    - env: TOXENV=py34-dj17
    - env: TOXENV=py27-dj18
    - env: TOXENV=py33-dj18
    - env: TOXENV=py34-dj18

# Package installation
install:
  - pip install tox coveralls

# Run tests
script:
  - tox

# Call subsequent services
after_success:
  - coveralls

# Automate deployment after success
deploy:
  provider: pypi
  user: timorieber
  password:
    secure: Au48TJyLYVJD2rDL2811F2XsnPdaLQyfGIWN8JtVC5TfB4UA0tgbltrd/joY4EIAORLjuPBgH5F6uEYjtND0kkRxW7WqiICjPEbb/aFYJbb2rrxeYF4fCavlXcedtEw9UDSPyIpPDbMNqEQM7VjTWRW3BSSDpyyvKaYHs/eGB9w=
  on:
    tags: true
    repo: timorieber/django-bootstrap-ui
  distributions: sdist bdist_wheel
